---
- hosts: all
  become: true
  tasks:

    - name: Install Python 3 and pip3
      apt:
        name:
          - python3
          - python3-pip    
        state: present

    - name: Set pip3 as the default pip
      apt:
        name: python3-pip
        state: present

